<?php
define('BUSINIAO_API_VERSION','1.1.1');
define('BUSINIAO_API_HOST','http://wxblock.systempanel.org/api/');
define('BUSINIAO_API_TYPE_DomainShortUrl','DomainShortUrl.json');
define('BUSINIAO_API_TYPE_GetWechatShortUrl','GetWechatShortUrl.json');
define('BUSINIAO_API_TYPE_GetWeiboShortUrl','GetWeiboShortUrl.json');
define('BUSINIAO_API_TYPE_SingleShortUrl','SingleShortUrl.json');
define('BUSINIAO_API_TYPE_UrlCheck','UrlCheck.json');
define('BUSINIAO_API_TYPE_UrlCycleCheck','UrlCycleCheck.json');
